// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MyTask.Models
{
    public partial class Calender
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [StringLength(120)]
        public string Title { get; set; }
        public string Note { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Time { get; set; }
        [Column("User_id")]
        public int? UserId { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("Calender")]
        public virtual User User { get; set; }
    }
}