// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MyTask.Models
{
    public partial class User
    {
        public User()
        {
            Calender = new HashSet<Calender>();
            Contacts = new HashSet<Contacts>();
            Notes = new HashSet<Notes>();
            Tasks = new HashSet<Tasks>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("User_Name")]
        [StringLength(20)]
        public string UserName { get; set; }
        [Column("User_Phone")]
        [StringLength(20)]
        public string UserPhone { get; set; }
        [Column("User_Email")]
        [StringLength(50)]
        public string UserEmail { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<Calender> Calender { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Contacts> Contacts { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Notes> Notes { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}